package com.joniaranguri.platzi.android.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFB1C5FF)
val md_theme_dark_onPrimary = Color(0xFF002C71)
val md_theme_dark_primaryContainer = Color(0xFF1C438F)
val md_theme_dark_onPrimaryContainer = Color(0xFFDAE2FF)
val md_theme_dark_secondary = Color(0xFFA4D64A)
val md_theme_dark_onSecondary = Color(0xFF233600)
val md_theme_dark_secondaryContainer = Color(0xFF354E00)
val md_theme_dark_onSecondaryContainer = Color(0xFFBFF364)
val md_theme_dark_tertiary = Color(0xFFACC7FF)
val md_theme_dark_onTertiary = Color(0xFF002F68)
val md_theme_dark_tertiaryContainer = Color(0xFF0A458E)
val md_theme_dark_onTertiaryContainer = Color(0xFFD7E2FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001D31)
val md_theme_dark_onBackground = Color(0xFFCDE5FF)
val md_theme_dark_surface = Color(0xFF001D31)
val md_theme_dark_onSurface = Color(0xFFCDE5FF)
val md_theme_dark_surfaceVariant = Color(0xFF44464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC5C6D0)
val md_theme_dark_outline = Color(0xFF8F9099)
val md_theme_dark_inverseOnSurface = Color(0xFF001D31)
val md_theme_dark_inverseSurface = Color(0xFFCDE5FF)
val md_theme_dark_inversePrimary = Color(0xFF395BA9)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB1C5FF)
val md_theme_dark_outlineVariant = Color(0xFF44464F)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF121F3D)